# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - master
      - releases/*
      - feature/*
    exclude:
      - releases/old*
      - feature/*-working
  paths:
    exclude:
      - docs/*.md
pr:
  - master
  - release/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo Starting the build
        mvn -B -q package -DskipTests
      displayName: 'Build with Maven'
    - task: DockerCompose@0
      displayName: "Starting Database"
      inputs:
        dockerComposeFile: "./docker-compose.yml"
        action: Run services
 #       serviceName: "mongodb"
    - script: |
        sleep 10
        docker ps -a
      displayName: "Display Docker Services"
    - script: |
        mvn -B -q clean verify -Pcoverage
      displayName: 'Running Tests'

      # Publish code coverage results
      # Publish Cobertura or JaCoCo code coverage results from a build
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo' # Available options: 'JaCoCo', 'Cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
        #pathToSources: # Optional
        reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco/'
        #additionalCodeCoverageFiles: # Optional
        #failIfCoverageEmpty: false # Optional

      # Publish Test Results
      # Publish test results to Azure Pipelines
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
        testResultsFiles: '**/TEST-*.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)/target' # Optional
      #mergeTestResults: false # Optional
      #failTaskOnFailedTests: false # Optional
      #testRunTitle: # Optional
      #buildPlatform: # Optional
      #buildConfiguration: # Optional
      #publishRunAttachments: true # Optional

