version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@3.2.5
executors:
  ubuntu:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true    # default - false
  docker-mongo:
    docker:
      - image: cimg/openjdk:17.0
      - image: mongo:latest
jobs:
  build:
    executor: ubuntu
    steps:
      - run:
          name: "Install JDK 17"
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            java -version
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn -q test verify -Pcoverage
      - maven/process_test_results
      - codecov/upload:
          when: on_success
workflows:
  build:
    jobs:
      - build
      # filters:
      #   branches:
      #     only:
      #       - master
