version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@3.2.5
executors:
  ubuntu:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true    # default - false
  docker-mongo:
    docker:
      - image: cimg/openjdk:17.0
      - image: mongo:latest
jobs:
  build:
    executor: ubuntu
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn -q test verify -Pcoverage
      - maven/process_test_results
      - codecov/upload:
          when: on_success
workflows:
  build:
    jobs:
      - build
      # filters:
      #   branches:
      #     only:
      #       - master
